name: "Deploy app to Azure Webapp"
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Azure"

    steps:
      - uses: action/checkout@v2

      - name: use node.js v14
        uses: actions/setup-node@v1

      - name: npm install
        run: npm install
      
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

   